Repository teamb-prince/pinterest_prince_go_2, pull requests merged in 2020-06, with the labels that each got.

#12 [Add] token Table & Token Fixtures
  fixtures/01-test-fixture.sql
  migrations/000004_token.down.sql
  migrations/000004_token.up.sql
Labels: enhancement

#16 [fix] GetImages function
  server/handlers/image_handler.go
  server/handlers/image_helpers.go
Labels: bug

#17 [update] images schema (+description)
  models/view/images.go
  server/handlers/image_handler.go
Labels: enhancement

#20 [delete] comment out / debug log
  api/awsmanager/aws.go
  auth/auth.go
  models/db/images.go
  models/db/user.go
  server/board_handler_test.go
  server/handlers/board_handler.go
  server/handlers/image_handler.go
  server/handlers/image_helpers.go
  server/handlers/pin_handler.go
  server/handlers/user_handler.go
  server/pin_handler_test.go
  server/server.go
  server/topic_handler_test.go
  server/user_handler_test.go
Labels: code review

#21 [add] fixtures
  fixtures/01-test-fixture.sql
Labels: enhancement

#24 [fix] PinRequest struct
  models/view/pin.go
Labels: wontfix

#26 [update/fix] POST /users
  go.mod
  models/db/user.go
  models/view/user.go
  server/handlers/helpers.go
  server/handlers/user_handler.go
Labels: wontfix

#28 [add] POST /login
  .gitignore
  auth/auth.go
  fixtures/01-test-fixture.sql
  migrations/000004_token.up.sql
  mocks/datastorage.go
  models/db/auth.go
  models/db/datastorage.go
  models/db/user.go
  models/view/auth.go
  server/handlers/auth_handler.go
  server/server.go
Labels: enhancement

#32 [add] GET /discover
  mocks/datastorage.go
  models/db/datastorage.go
  models/db/pin.go
  server/handlers/pin_handler.go
  server/server.go
Labels: enhancement

#33 [update] pin schema
  fixtures/01-test-fixture.sql
  migrations/000003_pin.up.sql
  models/db/pin.go
  models/view/pin.go
  server/handlers/pin_handler.go
Labels: enhancement

#37 [add] fixtures
  fixtures/01-test-fixture.sql
Labels: enhancement
